export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";

export const CONDUCT_TEST = "CONDUCT_TEST";
export const CONDUCT_TEST_ERROR = "CONDUCT_TEST_ERROR";

export const CREATE_PATIENT = "CREATE_PATIENT";
export const CREATE_PATIENT_ERROR = "CREATE_PATIENT_ERROR";

export const EDIT_PATIENT = "EDIT_PATIENT";
export const EDIT_PATIENT_ERROR = "EDIT_PATIENT_ERROR";

export const UPDATE_TEST_RESULT = "UPDATE_TEST_RESULT";
export const UPDATE_TEST_RESULT_ERROR = "UPDATE_TEST_RESULT_ERROR";

export const LISTEN_FOR_FEED_DATA = "LISTEN_FOR_FEED_DATA";
export const LISTEN_FOR_FEED_DATA_ERROR = "LISTEN_FOR_FEED_DATA_ERROR";

export const POST_FEED = "POST_FEED";
export const POST_FEED_ERROR = "POST_FEED_ERROR";

export const GET_FEEDS = "GET_FEEDS";
export const GET_FEEDS_ERROR = "GET_FEEDS_ERROR";

export const GET_ALL_TEST_RESULTS = "GET_ALL_TEST_RESULTS";
export const GET_ALL_TEST_RESULTS_ERROR = "GET_ALL_TEST_RESULTS_ERROR";

export const GET_TEST_RESULTS_ORDER_BY_DATE = "GET_TEST_RESULTS_ORDER_BY_DATE";
export const GET_TEST_RESULTS_ORDER_BY_DATE_ERROR =
  "GET_TEST_RESULTS_ORDER_BY_DATE_ERROR";

export const GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_HEALTHY =
  "GET_TEST_RESULTS_GROUPED_BY_HEALTHY";
export const GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_HEALTHY_ERROR =
  "GET_TEST_RESULTS_GROUPED_BY_HEALTHY_ERROR";

export const GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_HIGH_RISK =
  "GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_HIGH_RISK";
export const GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_HIGH_RISK_ERROR =
  "GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_HIGH_RISK_ERROR";

export const GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_NONE =
  "GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_NONE";
export const GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_NONE_ERROR =
  "GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_NONE_ERROR";

export const GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_HIGH_RISK =
  "GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_HIGH_RISK";
export const GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_HIGH_RISK_ERROR =
  "GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_HIGH_RISK_ERROR";

export const GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_NONE =
  "GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_NONE";
export const GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_NONE_ERROR =
  "GET_TEST_RESULTS_MATCH_BY_NEGATIVE_GROUP_BY_NONE_ERROR";

export const GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_NOT_HIGH_RISK =
  "GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_NOT_HIGH_RISK";
export const GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_NOT_HIGH_RISK_ERROR =
  "GET_TEST_RESULTS_MATCH_BY_POSITIVE_GROUP_BY_NOT_HIGH_RISK_ERROR";

export const GET_TEST_RESULTS_MATCH_BY_POSITIVE_ORDER_BY_DATE =
  "GET_TEST_RESULTS_MATCH_BY_POSITIVE_ORDER_BY_DATE";
export const GET_TEST_RESULTS_MATCH_BY_POSITIVE_ORDER_BY_DATE_ERROR =
  "GET_TEST_RESULTS_MATCH_BY_POSITIVE_ORDER_BY_DATE_ERROR";

export const GET_TEST_RESULTS_MATCH_BY_NEGATIVE_ORDER_BY_DATE =
  "GET_TEST_RESULTS_MATCH_BY_NEGATIVE_ORDER_BY_DATE";
export const GET_TEST_RESULTS_MATCH_BY_NEGATIVE_ORDER_BY_DATE_ERROR =
  "GET_TEST_RESULTS_MATCH_BY_NEGATIVE_ORDER_BY_DATE_ERROR";
